#!/bin/bash

# MIT License
#
# Copyright (c) 2025  M. Alexander Perez
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Check if the user provided enough arguments
if [ $# -lt 2 ]; then
    echo "Usage: docker-flatten <source-image> <new-image-name>"
    exit 1
fi

# Assign arguments to variables
SOURCE_IMAGE=$1
NEW_IMAGE=$2

# Create a container from the source image
CONTAINER_ID=$(docker create "$SOURCE_IMAGE")

# Export the container's filesystem to a tarball and import it as a new image
docker export "$CONTAINER_ID" | docker import - "$NEW_IMAGE"

# Remove the temporary container
docker rm "$CONTAINER_ID"

# Output the result
echo "Flattened image created: $NEW_IMAGE"
